version: 2.1

references:
  defaults: &defaults
    environment:
      TEAM_NAME: ciam
      APPLICATION_NAME: customer-api
      VAULT_ADDR: https://vault.factory.adeo.cloud
      VAULT_NAMESPACE: adeo/habitation-social-platform-community

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    environment:
      PREFIX_DOCKER_HUB: aallou
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: get version from package.json
          command: |
            echo "pwd"
            ls
            echo "export VERSION=$(node -p -e "require('./package.json').version")" >> $BASH_ENV
            env
            echo $VERSION
      - run:
          name: build image
          command: |
            pwd
            echo $VERSION
            docker --version
            docker build -t $PREFIX_DOCKER_HUB/node-app:$VERSION .
      - run:
          name: push image onto dockerhub
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD https://hub.docker.com
            docker push $PREFIX_DOCKER_HUB/node-app:$VERSION

workflows:
  version: 2
  build:
    jobs:
      - build
